import { useQuery } from '@tanstack/react-query'
import { ArrowRight, ArrowUpRight, Check, CheckCheck, ChevronRight, CircleHelp, Database, FlaskConical, Layers3, Radio, ShieldCheck, Sparkles, Users, Wallet } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api } from '../../lib/api/client'
import { channel, money, number, risk, status, when } from '../../lib/format'
import { explainExclusionReason, explainNotice } from '../../lib/explanations'
import { Card, CardHeader, EmptyState, ErrorPanel, Skeleton, StatusPill } from '../../components/ui/common'
import { HelpButton } from '../../components/ui/HelpCenter'
import { CalculatorPromo } from '../calculator/CalculatorPromo'

export function OverviewPage() {
  const overview = useQuery({ queryKey: ['overview'], queryFn: ({ signal }) => api.overview(signal) })
  const runs = useQuery({ queryKey: ['runs', 1], queryFn: ({ signal }) => api.runs(1, signal), refetchInterval: query => query.state.data?.items.some(run => run.status === 'running' || run.status === 'queued') ? 3000 : false })
  if (overview.isPending && !overview.isError) return <div className="page-stack overview-loading"><Card><Skeleton rows={4} /></Card><div className="bottom-grid"><Card><Skeleton rows={4} /></Card><Card><Skeleton rows={4} /></Card></div></div>
  if (!overview.data) return <ErrorPanel error={overview.error} onRetry={() => void overview.refetch()} title="Обзор недоступен" />
  const { dataset, limits, channels } = overview.data
  const last = runs.data?.items[0]
  const eligibleShare = dataset.customer_count ? Math.min(100, Math.max(0, dataset.eligible_customer_count / dataset.customer_count * 100)) : 0
  const canStart = dataset.eligible_customer_count > 0
  const active = last?.status === 'running' || last?.status === 'queued'
  if (dataset.customer_count === 0) return <div className="page-stack">
    <div className="section-intro"><p className="eyebrow">ПОДБОР ТАРИФНЫХ ПРЕДЛОЖЕНИЙ</p><h2>Данные аудитории пока недоступны</h2><p>Помощник подбирает, кому и какой тариф предложить. Для расчёта нужны учебные данные об абонентах: их текущие тарифы и выручка.</p></div>
    {overview.isError && <ErrorPanel error={overview.error} title="Обновление недоступно — показаны последние данные" onRetry={() => void overview.refetch()} />}
    {dataset.notices.map((notice, index) => <div key={index} className={`notice-line notice-${notice.severity}`}><CircleHelp size={17} aria-hidden="true" /><span>{explainNotice(notice).text}</span></div>)}
    <Card><EmptyState title="Нет профилей для анализа" text="Проверьте источник данных и обновите обзор после загрузки аудитории." action={<button className="button button-secondary" onClick={() => void overview.refetch()}>Обновить обзор</button>} /></Card>
    <Link to={active ? `/runs/${last.id}` : '/runs'} className="text-link">{active ? 'Открыть текущий расчёт' : 'Открыть сохранённые запуски'} <ArrowRight size={17} aria-hidden="true" /></Link>
  </div>
  return <div className="page-stack overview-page">
    {overview.isError && <ErrorPanel error={overview.error} title="Обновление недоступно — показаны последние данные" onRetry={() => void overview.refetch()} />}
    <div className="page-intro overview-intro"><div><p className="eyebrow">ПОМОЩНИК ПО ТАРИФНЫМ ПРЕДЛОЖЕНИЯМ</p><h2>Кому предложить тариф<br /><em>и какой эффект ожидать</em></h2><p>OrbitDuo изучает абонентов и составляет план: кому предложить какой тариф, как связаться и сколько это будет стоить.</p></div><HelpButton className="button button-secondary">Как пользоваться</HelpButton></div>
    <section className="studio-hero" aria-labelledby="hero-title">
      <div className="hero-copy"><span className="hero-label"><Sparkles size={15} aria-hidden="true" /> НАЧНИТЕ С ПОДБОРА</span><h2 id="hero-title">Получите план предложений<br /><span>с объяснением каждого выбора.</span></h2><p>Кампания — предложение одного тарифа выбранной группе через один способ связи. Помощник проверит варианты на небольших группах и выберет кампании в пределах бюджета.</p><div className="hero-actions">{active || canStart ? <Link className="button button-primary" to={active ? `/runs/${last.id}` : '/runs/new'}>{active ? 'Продолжить наблюдение' : 'Подобрать кампании'} <ArrowRight size={18} aria-hidden="true" /></Link> : <button className="button button-primary" disabled>Нет доступной аудитории</button>}<span><ShieldCheck size={15} aria-hidden="true" /> {overview.data.mode === 'demo' ? 'Учебный пример' : 'Учебный расчёт'}</span></div><small>{active ? 'Расчёт уже идёт. Откройте его, чтобы увидеть текущий этап.' : 'Данные об абонентах учебные. Реальные сообщения не отправляются.'}</small></div>
      <div className="hero-workflow" aria-label="Как устроен подбор"><div className="workflow-heading"><span>ЧТО СДЕЛАЕТ ПОМОЩНИК</span><span className="workflow-orbit" aria-hidden="true">↗</span></div><div className="workflow-row"><span className="workflow-icon"><Database size={18} aria-hidden="true" /></span><div><strong>Изучит абонентов</strong><p>Проверит тарифы и данные о выручке</p></div><span className="workflow-index">01</span></div><div className="workflow-row"><span className="workflow-icon"><FlaskConical size={18} aria-hidden="true" /></span><div><strong>Проверит предложения</strong><p>Проведёт пробные расчёты — пилоты</p></div><span className="workflow-index">02</span></div><div className="workflow-row"><span className="workflow-icon"><CheckCheck size={18} aria-hidden="true" /></span><div><strong>Составит план</strong><p>Покажет аудиторию, расходы и прогноз</p></div><span className="workflow-index">03</span></div></div>
    </section>
    <CalculatorPromo />
    <div className="overview-resources" aria-label="Ограничения подбора">
      <div><Wallet size={19} aria-hidden="true" /><span>Бюджет на связь<strong>{money(limits.budget)}</strong><small>Фиксирован для проверок и плана</small></span></div>
      <div><Users size={19} aria-hidden="true" /><span>Доступные контакты<strong>{number(limits.contacts)}</strong><small>Включая повторные попытки</small></span></div>
      <div><FlaskConical size={19} aria-hidden="true" /><span>Проверки предложений<strong>до {number(limits.pilots)} <em>пилотов</em></strong><small>По {number(limits.pilot_size_min)}–{number(limits.pilot_size_max)} абонентов</small></span></div>
      <div><Layers3 size={19} aria-hidden="true" /><span>Финальный план<strong>до {number(limits.final_campaigns)} <em>кампаний</em></strong><small>До {number(limits.customers_per_campaign)} абонентов в каждой</small></span></div>
    </div>
    <div className="overview-grid">
      <Card className="audience-overview"><CardHeader eyebrow="ДАННЫЕ ДЛЯ РЕШЕНИЯ" title="Ваша аудитория" aside={<Link to="/audience" className="text-link">Подробнее <ArrowUpRight size={16} aria-hidden="true" /></Link>} />
        <div className="big-metric"><strong>{number(dataset.customer_count)}</strong><span>абонентских профилей</span></div>
        <div className="audience-composition" aria-hidden="true"><span style={{ width: `${eligibleShare}%` }} /></div><div className="composition-legend"><span><i /><b>{number(dataset.eligible_customer_count)}</b> доступны для подбора</span><span><i /><b>{number(dataset.excluded_customer_count)}</b> исключены</span></div>
        <div className="baseline"><div className="baseline-label"><span>Ожидаемая выручка без новых предложений</span><HelpButton query="ARPU" className="metric-help"><span className="sr-only">Что означает исходная выручка</span></HelpButton></div><strong>{money(dataset.baseline_revenue)}</strong><small>Сколько вся аудитория может принести на текущих тарифах. Суммы указаны в условных единицах (у.е.).</small></div>
        <Link className="audience-card-link" to="/audience"><span>Посмотреть группы и тарифы</span><ArrowRight size={17} aria-hidden="true" /></Link>
      </Card>
      <Card className="history-overview"><CardHeader eyebrow="СОХРАНЁННЫЙ РЕЗУЛЬТАТ" title="Последний запуск" aside={last && <Link to="/runs" className="text-link">Вся история <ArrowUpRight size={16} aria-hidden="true" /></Link>} />
        {runs.error && <ErrorPanel error={runs.error} title="Не удалось обновить историю" onRetry={() => void runs.refetch()} />}{runs.isPending ? <Skeleton rows={4} /> : last ? <div className="last-run"><div><StatusPill tone={last.status === 'completed' ? last.forecast_net_gain == null ? 'neutral' : last.forecast_net_gain <= 0 ? 'warning' : 'positive' : last.status === 'failed' ? 'negative' : 'neutral'}>{status(last.status)}</StatusPill><span>{when(last.created_at)}</span></div><h3>{risk(last.config.risk_profile)} подход</h3><p>Сценарий № {last.config.seed} · Сохранённый расчёт</p><div className="last-run-metrics"><div><span>Прогноз эффекта</span><strong className={last.forecast_net_gain != null && last.forecast_net_gain < 0 ? 'negative-text' : ''}>{money(last.forecast_net_gain)}</strong></div><div><span>Проверка в симуляции</span><strong className={last.local_net_gain != null && last.local_net_gain < 0 ? 'negative-text' : ''}>{money(last.local_net_gain)}</strong></div></div><Link to={`/runs/${last.id}`} className="button button-secondary">{active ? 'Наблюдать за расчётом' : 'Открыть запуск'} <ArrowRight size={16} aria-hidden="true" /></Link></div> : <div className="first-run"><span className="first-run-icon"><Layers3 size={27} aria-hidden="true" /><span>+</span></span><h3>Здесь появится ваш первый план</h3><p>После расчёта вы увидите выбранные предложения, объяснения и результат. Начните с настроек подбора.</p><div className="first-run-outcomes"><span><Check size={14} aria-hidden="true" /> Результаты проверок</span><span><Check size={14} aria-hidden="true" /> Прогноз эффекта</span><span><Check size={14} aria-hidden="true" /> План и отчёт</span></div>{canStart && <Link to="/runs/new" className="text-link">Настроить первый запуск <ArrowRight size={16} aria-hidden="true" /></Link>}</div>}
      </Card>
    </div>
    <section className="getting-started" aria-labelledby="getting-started-title"><div className="section-row"><div><p className="eyebrow">БЫСТРЫЙ СТАРТ</p><h2 id="getting-started-title">Три шага к понятному результату</h2></div><span>Вы выбираете подход. Программа делает расчёт.</span></div><div className="start-steps"><Link to="/audience"><span className="start-number">01</span><h3>Посмотрите аудиторию <ArrowUpRight size={17} aria-hidden="true" /></h3><p>Узнайте, какие тарифы уже есть у абонентов и хватает ли данных для подбора.</p><span className="step-link">Перейти к аудитории <ArrowRight size={15} aria-hidden="true" /></span></Link><Link to="/runs/new"><span className="start-number">02</span><h3>Запустите подбор <ArrowUpRight size={17} aria-hidden="true" /></h3><p>Для первого раза оставьте сбалансированный подход и нажмите «Подобрать кампании». Бюджет и лимиты уже заданы.</p><span className="step-link">Настроить подбор <ArrowRight size={15} aria-hidden="true" /></span></Link><div><span className="start-number">03</span><h3>Изучите результат</h3><p>Прочитайте разбор, посмотрите, что стоит проверить, и скачайте план. Чтобы сравнить другой подход, создайте новый расчёт.</p><HelpButton query="Как читать готовый план" className="step-link">Как читать результат</HelpButton></div></div></section>
    <Card className="quality-card"><ShieldCheck size={21} aria-hidden="true" /><div><strong>Хватает ли данных для подбора</strong><p>{dataset.exclusion_reason ? explainExclusionReason(dataset.exclusion_reason).text : 'Перед подбором программа проверяет, для каких абонентов хватает исходных данных.'} {dataset.excluded_customer_count > 0 && `${number(dataset.excluded_customer_count)} записей показаны отдельно в разделе «Аудитория».`}</p></div><Link to="/audience" className="text-link">Проверить качество <ChevronRight size={16} aria-hidden="true" /></Link></Card>
    {dataset.notices.length > 0 && <div className="overview-notices">{dataset.notices.map((notice, index) => <div key={`${notice.code}-${index}`} className={`notice-line notice-${notice.severity}`}><CircleHelp size={17} aria-hidden="true" /><span>{explainNotice(notice).text}{notice.affected_count != null && <> · Записей: {number(notice.affected_count)}</>}</span></div>)}</div>}
    <details className="channel-details"><summary><Radio size={18} aria-hidden="true" /><span>Как можно связаться с абонентом и сколько это стоит?</span><span className="disclosure-plus" aria-hidden="true">+</span></summary><div><p>Канал — способ связи: например, СМС или звонок. Программа выбирает его вместе с тарифом. Цена одной попытки связи задана для учебного расчёта.</p><div className="channel-list">{channels.map(item => <div key={item.code}><strong>{channel(item.code)}</strong><span>{money(item.cost_per_contact)} <small>/ попытка</small></span></div>)}</div></div></details>
  </div>
}
