import { expect, test, type Page } from '@playwright/test'

const countInput = (page: Page) => page.getByRole('spinbutton', { name: 'Сколько абонентов охватить', exact: true })
const conversionInput = (page: Page) => page.getByRole('spinbutton', { name: 'Вероятность перехода', exact: true })
const liftInput = (page: Page) => page.getByRole('spinbutton', { name: 'Изменение выручки после перехода', exact: true })
const budgetInput = (page: Page) => page.getByRole('spinbutton', { name: 'Бюджет на связь', exact: true })

test.beforeEach(async ({ page }) => {
  await page.goto('/calculator')
  await expect(page.getByRole('heading', { name: 'Калькулятор эффекта', exact: true })).toBeVisible()
  await expect(page.getByTestId('scenario-net')).toBeVisible()
})

test('updates the estimate immediately from precise values and keyboard-operated sliders', async ({ page }) => {
  // This demo group has 11 people and total baseline revenue of 82,638.48 CU.
  // A 10% lift at a 5% channel-adjusted response yields 413.1924 CU, shown as 413.
  await page.getByRole('combobox', { name: 'Кому предложить' }).selectOption('0')
  await expect(countInput(page)).toHaveValue('11')
  await expect(page.getByTestId('scenario-net')).toHaveText('413 у.е.')

  await conversionInput(page).fill('20')
  await expect(page.getByTestId('scenario-net')).toHaveText('826 у.е.')
  const slider = page.getByRole('slider', { name: 'Вероятность перехода: ползунок', exact: true })
  await expect(slider).toHaveValue('20')
  await slider.focus()
  await slider.press('ArrowRight')
  await expect(conversionInput(page)).toHaveValue('21')
  await expect(page.getByTestId('scenario-net')).toHaveText('868 у.е.')
  await slider.press('Home')
  await expect(conversionInput(page)).toHaveValue('0')
  await expect(page.getByTestId('scenario-net')).toHaveText('0 у.е.')
  await expect(page.getByText('При этих условиях эффект равен нулю', { exact: true })).toBeVisible()
})

test('distinguishes negative effects from zero contacts and rejects incomplete inputs', async ({ page }) => {
  await page.getByRole('combobox', { name: 'Кому предложить' }).selectOption('0')
  await page.getByRole('combobox', { name: 'Как связаться' }).selectOption('sms')
  await conversionInput(page).fill('0')
  await expect(page.getByTestId('scenario-net')).toHaveText('-44 у.е.')
  await expect(page.getByTestId('scenario-net')).toHaveClass(/negative/)
  await expect(page.getByText('При этих условиях эффект отрицательный', { exact: true })).toBeVisible()
  await conversionInput(page).fill('10')
  await liftInput(page).fill('-10')
  await expect(page.getByTestId('scenario-net')).toHaveText('-581 у.е.')

  await countInput(page).fill('0')
  await expect(page.getByTestId('scenario-net')).toHaveText('0 у.е.')
  await expect(page.getByTestId('scenario-cost')).toHaveText('0 у.е.')
  await expect(page.getByText('В этом сценарии нет контактов', { exact: true })).toBeVisible()

  await countInput(page).fill('')
  await expect(countInput(page)).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByRole('heading', { name: 'Проверьте значения' })).toBeVisible()
  await expect(page.getByTestId('scenario-net')).toHaveCount(0)
  await countInput(page).fill('1.5')
  await expect(countInput(page)).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByTestId('scenario-net')).toHaveCount(0)
  await countInput(page).fill('1')
  await expect(page.getByTestId('scenario-net')).toBeVisible()
})

test('caps paid contacts at the budget while allowing a free channel with zero budget', async ({ page }) => {
  await page.getByRole('combobox', { name: 'Как связаться' }).selectOption('call')
  await budgetInput(page).fill('320')
  await expect(countInput(page)).toHaveValue('1000')
  await expect(page.getByTestId('scenario-contacts')).toHaveText('2')
  await expect(page.getByTestId('scenario-cost')).toHaveText('320 у.е.')
  await expect(page.locator('.calculator-limits')).toContainText('Бюджета хватает на 2')

  await budgetInput(page).fill('0')
  await expect(page.getByTestId('scenario-contacts')).toHaveText('0')
  await expect(page.getByTestId('scenario-net')).toHaveText('0 у.е.')
  await page.getByRole('combobox', { name: 'Как связаться' }).selectOption('push')
  await expect(page.getByTestId('scenario-contacts')).toHaveText(/1\s000/)
  await expect(page.getByTestId('scenario-cost')).toHaveText('0 у.е.')
  await expect(page.getByTestId('scenario-net')).toHaveClass(/positive/)
  await expect(page.locator('.calculator-limits')).toHaveCount(0)
})

test('adjusts the contact range for a small group and resets all assumptions', async ({ page }) => {
  const initialNet = await page.getByTestId('scenario-net').textContent()
  await countInput(page).fill('5000')
  await page.getByRole('combobox', { name: 'Кому предложить' }).selectOption('0')
  await expect(countInput(page)).toHaveValue('11')
  await expect(countInput(page)).toHaveAttribute('max', '11')
  const contactsSlider = page.getByRole('slider', { name: 'Сколько абонентов охватить: ползунок', exact: true })
  await expect(contactsSlider).toHaveAttribute('max', '11')
  await countInput(page).fill('12')
  await expect(countInput(page)).toHaveAttribute('aria-invalid', 'true')
  await expect(page.getByTestId('scenario-net')).toHaveCount(0)
  await contactsSlider.focus()
  await contactsSlider.press('Home')
  await contactsSlider.press('End')
  await expect(countInput(page)).toHaveValue('11')
  await expect(page.getByTestId('scenario-net')).toBeVisible()

  await page.getByRole('combobox', { name: 'Как связаться' }).selectOption('digital_ads')
  await budgetInput(page).fill('50')
  await conversionInput(page).fill('25')
  await liftInput(page).fill('-20')
  await page.getByRole('button', { name: 'Сбросить калькулятор' }).click()
  await expect(page.getByRole('combobox', { name: 'Кому предложить' })).toHaveValue('all')
  await expect(page.getByRole('combobox', { name: 'Как связаться' })).toHaveValue('push')
  await expect(countInput(page)).toHaveValue('1000')
  await expect(budgetInput(page)).toHaveValue('100000')
  await expect(conversionInput(page)).toHaveValue('10')
  await expect(liftInput(page)).toHaveValue('10')
  await expect(page.getByTestId('scenario-net')).toHaveText(initialNet!)
})

test('applies channel comparisons without creating or modifying a saved run', async ({ page }) => {
  const posts: string[] = []
  page.on('request', request => { if (request.method() === 'POST') posts.push(request.url()) })
  const storedRuns = await page.evaluate(() => localStorage.getItem('orbitduo-demo-runs-v1'))
  const comparison = page.getByRole('region', { name: 'А если выбрать другой способ связи?' })
  await expect(comparison.getByRole('button')).toHaveCount(4)
  const sms = comparison.getByRole('button', { name: /^СМС / })
  const smsEstimate = await sms.locator('strong').textContent()
  await sms.click()
  await expect(page.getByRole('combobox', { name: 'Как связаться' })).toHaveValue('sms')
  await expect(sms).toHaveAttribute('aria-pressed', 'true')
  await expect(comparison.getByRole('button', { name: /^Уведомление в приложении / })).toHaveAttribute('aria-pressed', 'false')
  await expect(page.getByTestId('scenario-net')).toHaveText(smsEstimate!)
  await page.getByRole('combobox', { name: 'Как связаться' }).selectOption('call')
  await expect(comparison.getByRole('button', { name: /^Звонок / })).toHaveAttribute('aria-pressed', 'true')
  await expect(sms).toHaveAttribute('aria-pressed', 'false')

  await page.getByText('Как получилась эта сумма и чему можно доверять?', { exact: true }).click()
  await expect(page.locator('.calculator-formula')).toContainText('Калькулятор не знает, кто действительно перейдёт')
  await page.getByRole('link', { name: 'Перейти к подбору' }).click()
  await expect(page).toHaveURL(/\/runs\/new$/)
  expect(await page.evaluate(() => localStorage.getItem('orbitduo-demo-runs-v1'))).toBe(storedRuns)
  expect(posts).toEqual([])
})

test('keeps the live result visible while adjusting sliders on a 390px screen', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.setViewportSize({ width: 390, height: 844 })
  const liftSlider = page.getByRole('slider', { name: 'Изменение выручки после перехода: ползунок', exact: true })
  await liftSlider.scrollIntoViewIfNeeded()
  await liftSlider.focus()
  await liftSlider.press('End')
  await expect(liftInput(page)).toHaveValue('100')
  const preview = page.locator('.calculator-live-preview')
  await expect(preview).toBeInViewport()
  await expect(preview.locator('strong')).toHaveText((await page.getByTestId('scenario-net').textContent())!)
  await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1)).toBe(true)
  await page.screenshot({ path: 'test-results/calculator-mobile-controls.png' })
  await preview.click()
  await expect(page).toHaveURL(/#scenario-result$/)
  await expect(page.getByTestId('scenario-net')).toBeInViewport()
  await expect(page.locator('.calculator-result')).toHaveCSS('position', 'static')
  await page.screenshot({ path: 'test-results/calculator-mobile-result.png' })
  expect(errors).toEqual([])
})

test('explains an empty audience without presenting a fabricated estimate', async ({ page }) => {
  await page.evaluate(() => localStorage.setItem('orbitduo-demo-fixture', 'empty'))
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Нет доступной аудитории' })).toBeVisible()
  await expect(page.getByTestId('scenario-net')).toHaveCount(0)
  await expect(page.getByRole('slider', { name: 'Сколько абонентов охватить: ползунок', exact: true })).toBeDisabled()
  await expect(page.getByRole('region', { name: 'А если выбрать другой способ связи?' })).toHaveCount(0)
})
