import { expect, test } from '@playwright/test'

test('create → progress → reload → result → drawer → export', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Демо · синтетические данные')).toBeVisible()
  await page.getByRole('link', { name: 'Подобрать кампании', exact: true }).click()
  await page.getByRole('button', { name: 'Подобрать кампании' }).click()
  await expect(page).toHaveURL(/\/runs\/[0-9a-f]{8}-/)
  const runUrl = page.url()
  await expect(page.getByRole('heading', { name: 'Программа подбирает предложения' })).toBeVisible({ timeout: 6000 })
  await page.reload()
  await expect(page).toHaveURL(runUrl)
  await expect(page.getByRole('heading', { name: 'План готов' })).toBeVisible({ timeout: 25000 })
  const drawerTrigger = page.getByRole('button', { name: 'Подробности кампании 1' })
  await drawerTrigger.click()
  await expect(page.getByRole('dialog', { name: 'Подробности кампании' })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: 'Подробности кампании' })).not.toBeVisible()
  await expect(drawerTrigger).toBeFocused()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать план CSV' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^orbitduo-.*-campaigns\.csv$/)
  const reportPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Скачать отчёт JSON' }).click()
  expect((await reportPromise).suggestedFilename()).toMatch(/^orbitduo-.*-report\.json$/)
})

test('negative forecast is explained without a success claim', async ({ page }) => {
  await page.goto('/runs/new')
  await page.getByText('Номер сценария (необязательно)').click()
  await page.getByLabel('Seed локальной симуляции').fill('7')
  await page.getByRole('button', { name: 'Подобрать кампании' }).click()
  await expect(page.getByRole('heading', { name: 'Прогноз всего запуска отрицательный' })).toBeVisible({ timeout: 25000 })
  await expect(page.locator('.forecast-card .result-main')).toBeVisible()
  await expect(page.getByText('Резервный вариант', { exact: true })).toBeVisible()
})

test('failed run keeps its pilot journal and blocks export', async ({ page }) => {
  await page.goto('/runs/new')
  await page.getByText('Номер сценария (необязательно)').click()
  await page.getByLabel('Seed локальной симуляции').fill('13')
  await page.getByRole('button', { name: 'Подобрать кампании' }).click()
  await expect(page.getByRole('heading', { name: 'Расчёт завершился ошибкой' })).toBeVisible({ timeout: 20000 })
  await expect(page.getByRole('heading', { name: 'План не завершён' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Первый пилот завершён', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Скачать план CSV' })).toBeDisabled()
  await expect(page.getByRole('link', { name: /Повторить расчёт как новый запуск/ })).toBeVisible()
})
