import { expect, test } from '@playwright/test'

test.describe('in-product guidance', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/')
    await expect(page.getByText('Демо · синтетические данные')).toBeVisible()
  })

  test('searches explanations and recovers from an empty result', async ({ page }) => {
    await page.getByRole('button', { name: 'Справка', exact: true }).click()
    const help = page.getByRole('dialog', { name: 'Как пользоваться OrbitDuo' })
    const search = help.getByRole('textbox', { name: 'Поиск по справке' })
    await expect(help).toBeVisible()
    await search.fill('  arpu  ')
    await expect(help.getByText(/ARPU — средняя выручка на одного абонента/)).toBeVisible()
    await expect(help.getByRole('status')).toContainText('Найдено ответов:')

    await search.fill('несуществующая-подсказка-12345')
    await expect(help.getByRole('heading', { name: 'Такой подсказки пока нет' })).toBeVisible()
    await expect(help.getByRole('status')).toHaveText('Найдено ответов: 0')
    await help.getByRole('button', { name: 'Очистить поиск по справке' }).click()
    await expect(search).toHaveValue('')
    await expect(search).toBeFocused()
    await expect(help.getByRole('heading', { name: 'Такой подсказки пока нет' })).not.toBeVisible()
    await expect(help.getByRole('status')).toHaveText('От первого подбора до готового отчёта')

    await search.fill('другая-несуществующая-подсказка-54321')
    await help.getByRole('button', { name: 'Показать все ответы' }).click()
    await expect(search).toHaveValue('')
    await expect(search).toBeFocused()
    await expect(help.getByRole('heading', { name: 'Такой подсказки пока нет' })).not.toBeVisible()
    await expect(help.getByRole('status')).toHaveText('От первого подбора до готового отчёта')
  })

  test('focuses search when opened and restores the trigger after Escape', async ({ page }) => {
    const trigger = page.getByRole('button', { name: 'Справка', exact: true })
    await trigger.click()
    const help = page.getByRole('dialog', { name: 'Как пользоваться OrbitDuo' })
    await expect(help.getByRole('textbox', { name: 'Поиск по справке' })).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(help).not.toBeVisible()
    await expect(trigger).toBeFocused()

    await page.keyboard.press('Enter')
    await expect(help).toBeVisible()
    await help.getByRole('button', { name: 'Закрыть справку' }).click()
    await expect(help).not.toBeVisible()
    await expect(trigger).toBeFocused()
  })

  test('opens the relevant explanation directly from a metric hint', async ({ page }) => {
    const trigger = page.getByRole('button', { name: 'Что означает исходная выручка' })
    await trigger.click()
    const help = page.getByRole('dialog', { name: 'Как пользоваться OrbitDuo' })
    await expect(help).toBeVisible()
    await expect(help.getByRole('textbox', { name: 'Поиск по справке' })).toHaveValue('ARPU')
    await expect(help.getByText(/ARPU — средняя выручка на одного абонента/)).toBeVisible()
    await page.keyboard.press('Escape')
    await expect(help).not.toBeVisible()
    await expect(trigger).toBeFocused()

    await page.getByRole('button', { name: 'Справка', exact: true }).click()
    await expect(help.getByRole('textbox', { name: 'Поиск по справке' })).toHaveValue('')
  })
})

test('help navigation and browser Back close the dialog without stealing page focus', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'Справка', exact: true })
  await trigger.click()
  const help = page.getByRole('dialog')
  await help.getByRole('textbox', { name: 'Поиск по справке' }).fill('С чего начать')
  await help.getByRole('link', { name: 'Настроить подбор' }).click()
  await expect(page).toHaveURL(/\/runs\/new$/)
  await expect(help).not.toBeVisible()
  await expect(page.getByRole('main')).toBeFocused()
  await trigger.click()
  await expect(help.getByRole('textbox', { name: 'Поиск по справке' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(help).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(help).toBeVisible()
  await page.goBack()
  await expect(page).toHaveURL(/\/$/)
  await expect(help).not.toBeVisible()
  await expect(page.getByRole('main')).toBeFocused()
  await trigger.click()
  await expect(help.getByRole('textbox', { name: 'Поиск по справке' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(help).not.toBeVisible()
  await expect(trigger).toBeFocused()
})

test('local demo remains usable when the browser reports offline', async ({ page, context }) => {
  await page.goto('/audience')
  await expect(page.getByRole('heading', { name: 'Кого можно включить в план' })).toBeVisible()
  await context.setOffline(true)
  await page.getByRole('link', { name: 'Запуски', exact: true }).first().click()
  await expect(page.getByRole('heading', { name: 'Здесь появится ваш первый план' })).toBeVisible()
  await context.setOffline(false)
})

test('an unknown route offers working routes back to overview and history', async ({ page }) => {
  await page.goto('/unknown-guidance-route')
  await expect(page.getByRole('heading', { name: 'Страница не найдена' })).toBeVisible()
  await page.getByRole('link', { name: 'Вернуться на обзор' }).click()
  await expect(page).toHaveURL(/\/$/)
  await expect(page.getByRole('heading', { name: /Кому предложить тариф/ })).toBeVisible()

  await page.goto('/another-unknown-guidance-route')
  await expect(page.getByRole('heading', { name: 'Страница не найдена' })).toBeVisible()
  await page.getByRole('main').getByRole('link', { name: 'История запусков' }).click()
  await expect(page).toHaveURL(/\/runs$/)
  await expect(page.getByRole('heading', { name: 'Страница не найдена' })).not.toBeVisible()
  await expect(page.getByRole('heading', { name: 'История запусков', exact: true })).toBeVisible()
})
