import { expect, test } from '@playwright/test'

test('saves a named scenario with notes, restores exact values and deletes it', async ({ page }) => {
  await page.goto('/calculator')
  await expect(page.getByTestId('scenario-net')).toBeVisible()
  await page.getByRole('combobox', { name: 'Кому предложить' }).selectOption('0')
  await page.getByRole('spinbutton', { name: 'Вероятность перехода', exact: true }).fill('12.345')
  await page.getByRole('spinbutton', { name: 'Изменение выручки после перехода', exact: true }).fill('-7.89')
  await page.getByLabel('Шаг вероятности, п.п.').fill('3.456')
  const amount = await page.getByTestId('scenario-net').textContent()
  await page.getByLabel('Название сценария').fill('Небольшая группа')
  await page.getByLabel('Заметка', { exact: false }).fill('Проверить снижение выручки')
  await page.getByRole('button', { name: 'Сохранить сценарий', exact: true }).click()
  await expect(page.locator('#scenario-library').getByRole('status')).toContainText('сохранён в этом браузере')
  await page.reload()
  await page.getByRole('button', { name: 'Загрузить сценарий Небольшая группа' }).click()
  await expect(page.getByRole('combobox', { name: 'Кому предложить' })).toHaveValue('0')
  await expect(page.getByRole('spinbutton', { name: 'Вероятность перехода', exact: true })).toHaveValue('12.345')
  await expect(page.getByLabel('Шаг вероятности, п.п.')).toHaveValue('3.456')
  await expect(page.getByTestId('scenario-net')).toHaveText(amount!)
  await expect(page.getByText('Проверить снижение выручки', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Удалить сценарий Небольшая группа' }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: 'Загрузить сценарий Небольшая группа' })).toHaveCount(0)
})

test('shared URL reproduces precise conditions and source group without local storage', async ({ page, context }) => {
  await page.goto('/calculator')
  await expect(page.getByTestId('scenario-net')).toBeVisible()
  await page.getByRole('combobox', { name: 'Кому предложить' }).selectOption('0')
  await page.getByRole('combobox', { name: 'Как связаться' }).selectOption('sms')
  await page.getByRole('spinbutton', { name: 'Бюджет на связь', exact: true }).fill('30.123')
  await page.getByRole('spinbutton', { name: 'Вероятность перехода', exact: true }).fill('17.123')
  await page.getByLabel('Шаг вероятности, п.п.').fill('1.234')
  const expected = await page.getByTestId('scenario-net').textContent()
  await page.getByRole('button', { name: 'Получить ссылку', exact: true }).click()
  const url = await page.getByLabel('Ссылка с параметрами').inputValue()
  const payload = JSON.parse(new URL(url).searchParams.get('scenario')!)
  expect(payload.group).toEqual({ tariff: expect.any(String), arpu: expect.any(String) })
  expect(payload.datasetId).toBeTruthy()
  const recipient = await context.newPage()
  await recipient.goto(url)
  await expect(recipient.getByTestId('scenario-net')).toHaveText(expected!)
  await expect(recipient.getByRole('spinbutton', { name: 'Бюджет на связь', exact: true })).toHaveValue('30.123')
  await expect(recipient.getByRole('spinbutton', { name: 'Вероятность перехода', exact: true })).toHaveValue('17.123')
  await expect(recipient.getByLabel('Шаг вероятности, п.п.')).toHaveValue('1.234')
  await expect(recipient.getByRole('combobox', { name: 'Кому предложить' })).toHaveValue('0')
  payload.datasetId = 'another-dataset'
  const mismatched = new URL(url)
  mismatched.searchParams.set('scenario', JSON.stringify(payload))
  await recipient.goto(mismatched.toString())
  await expect(recipient.getByRole('alert')).toContainText('другого набора данных')
  await expect(recipient.getByRole('spinbutton', { name: 'Вероятность перехода', exact: true })).toHaveValue('10')
  await recipient.goto('/calculator?scenario=broken')
  await expect(recipient.getByRole('alert')).toContainText('повреждены')
  await expect(recipient.getByTestId('scenario-net')).toBeVisible()
  await recipient.close()
})

test('sensitivity keeps negative lift scenarios in financial order and validates its step', async ({ page }) => {
  await page.goto('/calculator')
  await expect(page.getByTestId('scenario-net')).toBeVisible()
  await page.getByRole('spinbutton', { name: 'Изменение выручки после перехода', exact: true }).fill('-20')
  const cautious = page.locator('.sensitivity-variant.cautious')
  const optimistic = page.locator('.sensitivity-variant.optimistic')
  await expect(cautious).toContainText('15%')
  await expect(optimistic).toContainText('5%')
  await expect(page.getByTestId('sensitivity-base')).toHaveText((await page.getByTestId('scenario-net').textContent())!)
  await page.getByLabel('Шаг вероятности, п.п.').fill('0')
  await expect(page.getByTestId('sensitivity-cautious')).toHaveText((await page.getByTestId('sensitivity-optimistic').textContent())!)
  await page.getByLabel('Шаг вероятности, п.п.').fill('')
  await expect(page.getByRole('alert')).toContainText('Введите шаг')
  await expect(page.getByRole('button', { name: 'Получить ссылку', exact: true })).toBeDisabled()
  await expect(page.getByTestId('scenario-net')).toBeVisible()
})

test('a browser storage refusal never produces a false save success', async ({ page }) => {
  await page.addInitScript(() => {
    const original = Storage.prototype.setItem
    Storage.prototype.setItem = function (key, value) {
      if (key === 'orbitduo-calculator-scenarios-v1') throw new DOMException('Storage full', 'QuotaExceededError')
      original.call(this, key, value)
    }
  })
  await page.goto('/calculator')
  await expect(page.getByTestId('scenario-net')).toBeVisible()
  await page.getByLabel('Название сценария').fill('Не сохранилось')
  await page.getByRole('button', { name: 'Сохранить сценарий', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Список остался прежним')
  await expect(page.getByRole('button', { name: 'Загрузить сценарий Не сохранилось' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Получить ссылку', exact: true }).click()
  await expect(page.getByLabel('Ссылка с параметрами')).toBeVisible()
})
